### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by Livelandr** [friztailo/gmod#2]
NO

_Originally posted by @friztailo in https://github.com/friztailo/gmod/issues/1#issuecomment-1950325782_

**Comment by Livelandr** [comment]
ale

**Comment by friztailo** [comment]
privet))))))))))))

**Comment by Livelandr** [comment]
![jRmRs408JDE](https://github.com/friztailo/gmod/assets/74109114/4b035df4-5964-4d29-847d-8cbc5e16c53e)

**Comment by Livelandr** [comment]
https://github.com/friztailo/gmod/assets/74109114/3c5bf688-85bf-418f-83c4-f6790ab6ec4c

**Comment by Livelandr** [comment]
![sergay](https://github.com/friztailo/gmod/assets/74109114/6519cbb3-e69d-4098-bd4a-e6adb3e1ba5a)
